### PR TITLE
348 tokens expiration

### LINKED ISSUE #348: Niceday API and broker token expires
The token of the niceday_api and the broker is generated only at the beginning, but it expires after 10 hours. The calls run through the API (triggers from celery and images upload) will fail as a consequence. 
We must either regenerate the token every 10h, or check the expiration and regenerate it in the calls.

### PR DESCRIPTION
**Pull request by wbaccinelli**
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/348

### CODE REVIEW

File: niceday-api/index.js [hunk 1]
```diff
@@ -45,10 +47,31 @@ function createNicedayApiServer() {
   return server;
 }
 
+function setupTokenRegeneration() {
+  const rule = new schedule.RecurrenceRule();
+  rule.hour = new schedule.Range(0, 23, 9);
```
Comment (raar1) [inline niceday-api/index.js]: So this returns an array of values in the range 0-23 (one day) every 9 hours, right?

Does that mean: 0:00, 09:00, 18:00 every day?
Or is it clever enough to do e.g.: 0:00, 09:00, 18:00, 03:00, 12:00, 21:00, 04:00 etc?
Because in the first case then more than 9 hours will pass between 18:00 and 09:00.

File: niceday-api/index.js [hunk 2]
```diff
@@ -45,10 +47,31 @@ function createNicedayApiServer() {
...
+
+  const job = schedule.scheduleJob(rule, () => {
+    authSdk.login(THERAPIST_EMAIL_ADDRESS, THERAPIST_PASSWORD)
+      .then((response) => {
+        app.set('therapistId', response.user.id);
+        app.set('token', response.token);
+      })
+      .catch((error) => {
+        throw Error(`Error during authentication: ${error}`);
```
Comment (raar1) [inline niceday-api/index.js:61]: Will it automatically retry if authentication fails?

Comment (raar1) [reply niceday-api/index.js:61]: (Is that a feature of schedule/job?)

File: niceday-api/service/MessagesService.js [hunk 3]
```diff
@@ -22,7 +28,19 @@ exports.sendTextMessage = function (req, body) {
     const chatSdk = new Chat();
     chatSdk.init(selectedServerEnv);
     chatSdk.connect(req.app.get('therapistId'), req.app.get('token'))
-      .catch((error) => reject(error));
+      .catch(() => {
```
Comment (raar1) [inline niceday-api/service/MessagesService.js:31]: OK, so does this code mean that any failure in authentication when sending a message will result in regenerating the token? That is therefore a backup for cases in which the scheduled job did not run for some reason?

**Review by raar1 — CHANGES_REQUESTED** [review]
Good work - I've left some review comments below. Only problem is the niceday-broker test keeps failing. I tried rerunning it to see if it was just flaky, but it seems to hang until it gets cancelled. Any idea what that could be?

File: niceday-api/index.js (hunk 1 above)
Comment (wbaccinelli) [reply niceday-api/index.js]: Good question, I was assuming the it runs every 9 hours, but checking the documentation more carefully, is I think you are right, and I incredibly didn't find a fast solution. I can set this to run every 8 hours, and it should be than safe.

File: niceday-api/index.js (hunk 2 above)
Comment (wbaccinelli) [reply niceday-api/index.js:61]: No, this should not retry, but if the token expired, and sending a message fails as a consequence, then this will be regenerated. I hope that this will be enough

File: niceday-api/service/MessagesService.js (hunk 3 above)
Comment (wbaccinelli) [reply niceday-api/service/MessagesService.js:31]: Yes, exactly, I tried to put this as a safety measure

**Comment by wbaccinelli** [comment]
> Good work - I've left some review comments below. Only problem is the niceday-broker test keeps failing. I tried rerunning it to see if it was just flaky, but it seems to hang until it gets cancelled. Any idea what that could be?

Yes, I saw this, I think that the job remains alive. I am looking into it
