### PR TITLE
383 messages optimization

### LINKED ISSUE #383: MessagesService in niceday_api not working properly
The the `MessagesService` implemented in the `niceday_api` is responding extremely slow. This is due to the fact that every time that the service is called by posting a message through the API, it will first login the user, wait for the result, then connect the chat service of NiceDay, wait for the result, notify the NiceDay service that the connection is active, wait for the result, and finally send the message and, of course, wait for the result. 

All the authentication steps must be done just once, and the service can then just send the message very fast.

### PR DESCRIPTION
**Pull request by wbaccinelli**
Fixes https://github.com/PerfectFit-project/virtual-coach-issues/issues/383

### CODE REVIEW

File: niceday-api/index.js [hunk 1]
```diff
@@ -31,11 +37,37 @@ const options = {
 const expressAppConfig = oas3Tools.expressAppConfig(path.join(__dirname, 'api/openapi.yaml'), options);
 const app = expressAppConfig.getApp();
 
+function setupChat(therapistId, token) {
```
Comment (raar1) [inline niceday-api/index.js:40]: Right... so, all this setup only needs to be done once (per session/token?). Before was it doing all this authentication stuff every time it sent a message?

**Review by raar1 — APPROVED** [review]
Good work man! I hadn't realised there was also some delay in the authentication stuff happening here

File: niceday-api/index.js (hunk 1 above)
Comment (wbaccinelli) [reply niceday-api/index.js:40]: Yes, isn't this great?
